site_name: "Design System v2 Documentation"
site_description: "Documentation for design system v2"
docs_dir: "docs"
repo_url:  ""
edit_uri: edit/main/docs/
plugins:
    - techdocs-core
    - ezlinks
markdown_extensions:
    - markdown_inline_mermaid
    - md_in_html
    -   mkpatcher:
            location: patcher.py
